// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface MarchMadness {
    forecasts: Forecasts;
    games:     Games;
}

export interface Forecasts {
    mens:   { [key: string]: MenValue };
    womens: { [key: string]: MenValue };
}

export interface MenValue {
    teams: Team[];
}

export interface Team {
    playin_flag: number;
    rd1_win:     number;
    rd2_win:     number;
    rd3_win:     number;
    rd4_win:     number;
    rd5_win:     number;
    rd6_win:     number;
    rd7_win:     number;
    results_to:  number;
    team_alive:  number;
    team_id:     number;
    team_name:   string;
    team_rating: number;
    team_region: TeamRegion;
    team_seed:   string;
    team_slot:   number;
}

export enum TeamRegion {
    Bridgeport = "Bridgeport",
    East = "East",
    Greensboro = "Greensboro",
    Midwest = "Midwest",
    South = "South",
    Spokane = "Spokane",
    West = "West",
    Wichita = "Wichita",
}

export interface Games {
    mens:   MenElement[];
    womens: MenElement[];
}

export interface MenElement {
    channel:         Channel;
    date:            string;
    datetime:        string;
    id:              number;
    live_margin1:    number | null;
    live_margin2:    number | null;
    live_prob:       number | null;
    madness:         number | null;
    period:          number;
    pregame_margin1: number;
    pregame_margin2: number;
    pregame_prob:    number;
    round:           number;
    score1:          number;
    score2:          number;
    secs:            number;
    status:          Status;
    status_detail:   string;
    team1:           string;
    team2:           string;
    winprobs:        Array<number[]>;
}

export enum Channel {
    Abc = "ABC",
    Cbs = "CBS",
    Espn = "ESPN",
    Espn2 = "ESPN2",
    Espnn = "ESPNN",
    Espnu = "ESPNU",
    Tbs = "TBS",
    Tnt = "TNT",
    TruTV = "truTV",
}

export enum Status {
    Post = "post",
    Pre = "pre",
}
